# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels conda-forge
  - conda config --add channels anaconda
  - conda config --set always_yes yes
  - conda config --set changeps1 no
  - conda config --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - conda env create -n glidertools-dev --file requirements.txt
  - source activate glidertools-dev
  - conda install pip
  - pip install .
  - pip install pytest-cov
  - pip install coveralls
  - pip install black
  - pip install flake8
  - pip install isort

script:
  - coverage run --source glidertools -m py.test
  - coverage report
  - ./ci/run-linter.sh

# after_success:
  # - coveralls  # not set up yet

# deploy:
#   provider: pypi
#   user: "__token__"
#   password: "Your PyPI API token, including the pypi- prefix"
