name: test_env_glidertools
channels:
  - conda-forge
dependencies:
  - numexpr
  - netCDF4
  - pandas<1.3.0 #temporary fix see #https://github.com/GliderToolsCommunity/GliderTools/issues/136
  - xarray
  - numpy
  - scikit-learn
  - scipy
  - tqdm
  - matplotlib
  - gsw
  - skyfield
  - pip
  - pip:
    - seawater
    - codecov
    - pytest-cov
    - pytest-xdist
